# YOLOv7 ğŸš€ by Ultralytics, AGPL-3.0 license
# Hyperparameters for low-augmentation COCO training from scratch
# python train.py --batch 64 --cfg yolov5n6.yaml --weights '' --data coco.yaml --img 640 --epochs 300 --linear
# See tutorials for hyperparameter evolution https://github.com/ultralytics/yolov5#tutorials

# ---------- ä¼˜åŒ–å™¨ å‚æ•° ----------
lr: 0.0001
momentum: 0.937
weight_decay: 0.000484

# ---------- é¢„çƒ­å™¨ å‚æ•° ----------
warmup_epochs: 3
warmup_momentum: 0.9  # warmup initial momentum
warmup_bias_lr: 0.1  # warmup initial bias lr

# ---------- æ•°æ®å¢å¼º å‚æ•° ----------
translate: 0.1  # image translation (+/- fraction)
scale: 0.1  # image scale (+/- gain)
flipud: 0.0  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)

# ---------- loss å‚æ•° ----------
anchor_t: 0.2
cls_pw: 1.0
obj_pw: 1.0
box: 3.54  # box loss gain
cls: 37.4  # cls loss gain
obj: 64.3  # obj loss gain (scale with pixels)