# YOLOv7 ğŸš€ by Ultralytics, AGPL-3.0 license
# Hyperparameters for low-augmentation COCO training from scratch
# python train.py --batch 64 --cfg yolov5n6.yaml --weights '' --data coco.yaml --img 640 --epochs 300 --linear
# See tutorials for hyperparameter evolution https://github.com/ultralytics/yolov5#tutorials

# ---------- ä¼˜åŒ–å™¨ å‚æ•° ----------
lr: 0.01
momentum: 0.937
weight_decay: 0.0005

# ---------- é¢„çƒ­å™¨ å‚æ•° ----------
warmup_iters: 3
warmup_factor: 0.1
warmup_method: 'linear'

# ---------- æ•°æ®å¢å¼º å‚æ•° ----------
translate: 0.1  # image translation (+/- fraction)
scale: 0.5  # image scale (+/- gain)

# ---------- loss å‚æ•° ----------
anchor_t: 4.0